### ISSUE TITLE
The "install.sh" script breaks ssh server on Raspberry Pi 4 8GB

### ISSUE THREAD

**Issue by maxhofidrone** [ctu-mrs/uav_core#18]
Hi,
I encounter some problems with installing uav_core on a Raspberry Pi 4 8GB RAM running Ubuntu server 18.04.5 for the use as onboard computer. Running this script as mentioned [here](https://github.com/ctu-mrs/uav_core) will break the ssh server after the next reboot. Connecting to a screen `sudo service ssh status` returns that the ssh server is now:
`Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset; enabled`
 `Active: inactive (dead)`
 It can be restarted then with `sudo service ssh start`. So I could quick-fix this issue with setting up a cron job restarting ssh after reboot.

I only partly understand what the install.sh script does- does it change any settings regarding the ssh server itself?

**Comment by klaxalk** [comment]
Hey, the `install.sh` within the `installation/` folder does not do anything with an ssh server nor ssh.
```bash
klaxalk@klaxalk-desktop2:~/mrs_workspace/src/uav_core/installation$ grep -nr -e "ssh"
klaxalk@klaxalk-desktop2:~/mrs_workspace/src/uav_core/installation$
```
I can't imagine right now how it could affect your ssh server connection. However, beware, the other `.ci/install.sh` script that is intended for the continuos integration by Github Actions freezes the OpenSSH-server package and it does some more things that make the GitHub actions run smoothly. Do not run the CI script, I am not sure what it would to a normal system.

**Comment by maxhofidrone** [comment]
Hello @klaxalk,
thanks for your answer. I also found the OpenSSH-server app hold in .ci/install.sh. Unfreeze also did not help. Anyway, I managed to install it without breaking the SSH server. Hopefully I can make a testflight later this week.

Best,

Max
